ARG OS_NAME=centos
ARG OS_VARIANT=stream
ARG OS_VERSION=9

FROM quay.io/${OS_NAME}/${OS_NAME}:${OS_VARIANT}${OS_VERSION}

ARG OS_NAME
ARG OS_VARIANT
ARG OS_VERSION

RUN dnf update -y && \
    dnf install -y 'dnf-command(config-manager)' 'dnf-command(copr)'

# install automotive-image-builder from copr
# this is done at this stage so it does not conflict with buildlog packages
RUN dnf copr enable -y @centos-automotive-sig/automotive-image-builder-dev && \
    dnf copr enable -y @osbuild/osbuild-stable && \
    dnf copr enable -y @centos-automotive-sig/osbuild-auto && \
    dnf install -y automotive-image-builder

# enable autosd repositories
RUN dnf config-manager --add-repo https://buildlogs.centos.org/${OS_VERSION}-${OS_VARIANT}/automotive/$(arch)/packages-main/ && \
    dnf config-manager --add-repo https://buildlogs.centos.org/${OS_VERSION}-${OS_VARIANT}/autosd/$(arch)/packages-main/

# install osbuild packages
RUN dnf install -y osbuild osbuild-luks2 osbuild-lvm2 osbuild-ostree osbuild-tools make sudo git jq qemu-img && \
    dnf install -y --nogpgcheck android-tools osbuild-auto && \
    dnf clean all
