ARG OS_NAME=centos
ARG OS_VARIANT=stream
ARG OS_VERSION=9

FROM quay.io/${OS_NAME}/${OS_NAME}:${OS_VARIANT}${OS_VERSION}-development

ARG OS_NAME
ARG OS_VARIANT
ARG OS_VERSION

RUN dnf update -y && \
    dnf install -y \
    'dnf-command(config-manager)' \
    'dnf-command(copr)'

# install automotive-image-builder from copr
# this is done at this stage so it does not conflict with buildlog packages
RUN dnf config-manager --set-enabled crb && \
    dnf copr enable -y @centos-automotive-sig/automotive-image-builder-dev && \
    dnf copr enable -y @osbuild/osbuild-stable && \
    dnf copr enable -y @centos-automotive-sig/osbuild-auto && \
    dnf install -y \
    automotive-image-builder && \
    dnf install -y --nogpgcheck\
    epel-release
# enable autosd repositories
RUN dnf config-manager --add-repo https://buildlogs.centos.org/${OS_VERSION}-${OS_VARIANT}/automotive/$(arch)/packages-main/ && \
    dnf config-manager --add-repo https://buildlogs.centos.org/${OS_VERSION}-${OS_VARIANT}/autosd/$(arch)/packages-main/

RUN dnf install -y \
    # Image build packages
    osbuild \
    osbuild-luks2 \
    osbuild-lvm2 \
    osbuild-ostree \
    osbuild-tools \
    make \
    sudo \
    git \
    jq \
    qemu-img && \
    dnf install -y --nogpgcheck \
    android-tools\
    osbuild-auto \
    # Dependencies to run a VM
    qemu-kvm \
    swtpm \
    # Some convenience packages \
    "@Development Tools" \
    bash-completion \
    emacs \
    strace \
    wget \
    fuse-sshfs \
    # Dependencies to build the kernel's RPM \
    rpm-build \
    hostname \
    openssl-devel \
    bc \
    binutils-devel \
    bpftool \
    clang \
    dwarves \
    gcc-plugin-devel \
    libcap-devel \
    libcap-ng-devel \
    libmnl-devel \
    llvm \
    net-tools \
    numactl-devel \
    perl-devel \
    python3-devel \
    python3-docutils \
    gcc-c++ \
    meson \
    ninja-build \
    rsync && \
    dnf clean all 
